# Use this file to templatize your application's native configuration files.
# See the docs at https://www.habitat.sh/docs/create-packages-configure/.
# You can safely delete this file if you don't need it.

#httpd.conf settings
serveradmin = "leo.fillmore@cort.com"
servername = {{hostname}}
serverport = "80"
listen = ["80"]
user = "hab"
group = "hab"
default_modules = [	"access_compat", "alias", "auth_basic", "authn_file", "authn_core", "authz_host", "authz_groupfile", "autoindex", "dir", "env", "filter", "headers", "log_config", "mime", "reqtimeout", "setenvif", "ssl", "status", "version", "rewrite", "proxy", "proxy_ajp", "proxy_connect", "proxy_express", "proxy_fcgi", "proxy_ftp", "proxy_http", "proxy_scgi", "proxy_wstunnel",  ]

# httpd-default settings
timeout = 60
keepalive = "On"
keepaliverequests = 100
keepalivetimeout = 5
serversignature = "Off"
servertokens = "Full"
accessfilename = ".htaccess"
canonicalname = "Off"
hostnamelookups = "Off"

# mpm settings
[mpm]
type = "prefork"
startservers = 5
serverlimit = 800
minspareservers = 5
maxspareservers = 10
maxrequestworkers = 250
maxconnectionsperchild = 0
# define these if the mpm is threaded like mpm_event or mpm_worker
threaded = false
threadsperchild = 64
threadlimit = 192

[mod_status]
allow = "127.0.0.1"
extended = "Off"

[mod_info]
allow = "127.0.0.1"

[mod_proxy]
require = "All Denied"
order = "Deny, Allow"
deny = "All"
allow = "None"

# php settings
[php]
version = 7



# cort-httpd settings
[srv]
port = "80"
host = "localhost"
